/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BD_Alumnos.com.app.mvc.view;
import BD_Alumnos.com.app.mvc.controller.OperacionesBD;
import BD_Alumnos.com.app.mvc.controller.Sesion;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

/**
 *JFrame para realizar las consultas sobre la tabla alumnos en la base de datos
 *
 * @author García Agustin Christian Santiago
 * @author Martínez Vera Josué Aldair
 * @author Mejía López Luis David
 * @author Solís Contreras Darian Giselle
 */

public class consultas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(consultas.class.getName());
    /** Controlador para las operaciones con la base de datos */
    private OperacionesBD operacionesBD;
    /** Nombre de la tabla de alumnos obtenida de la base de datos */
    private String tablaAlumnos;
    
    /**
     * Constructor que inicializa el JFrame, la conexión a la base de datos
     * y obtiene el nombre de la tabla de alumnos.
     */
    public consultas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Inicializa la conexión y nombre de la tabla de alumnos
        operacionesBD = new OperacionesBD(
            Sesion.getUsuario(),
            Sesion.getContrasena(),
            Sesion.getBaseDatos()
        );
        java.util.List<String> tablas = operacionesBD.mostrarTablas();
        if (!tablas.isEmpty()) {
            tablaAlumnos = tablas.get(0);
        } else {
            tablaAlumnos = null;
            JOptionPane.showMessageDialog(this, "No se encontró la tabla de alumnos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Muestra los resultados de una consulta en un JTable dentro de un JOptionPane.
     * Si no hay resultados o ocurre un error, muestra mensajes apropiados.
     * 
     * @param rs ResultSet con los datos de la consulta
     */
    private void mostrarResultados(ResultSet rs) {
        if (rs == null) {
            JOptionPane.showMessageDialog(this, "No hay resultados.", "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            ResultSetMetaData metaData = rs.getMetaData();
            int columnas = metaData.getColumnCount();

            DefaultTableModel modelo = new DefaultTableModel();
            // Agrega las columnas al modelo
            for (int i = 1; i <= columnas; i++) {
                modelo.addColumn(metaData.getColumnName(i));
            }
            int filas = 0;
            // Llena el modelo con las filas del ResultSet
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 1; i <= columnas; i++) {
                    fila[i - 1] = rs.getObject(i);
                }
                modelo.addRow(fila);
                filas++;
            }
            rs.close();

            if (filas == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron alumnos.", "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JTable tabla = new JTable(modelo);
                JScrollPane scroll = new JScrollPane(tabla);
                scroll.setPreferredSize(new java.awt.Dimension(500, 200));
                JOptionPane.showMessageDialog(this, scroll, "Resultados", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al mostrar resultados: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        buscarIDBg = new javax.swing.JPanel();
        indicacionLabel2 = new javax.swing.JLabel();
        sendBuscarId = new javax.swing.JButton();
        formattfieldId = new javax.swing.JFormattedTextField();
        buscarEdadBg = new javax.swing.JPanel();
        indicacionLabel3 = new javax.swing.JLabel();
        formattfieldEdad = new javax.swing.JTextField();
        sendBuscarEdad = new javax.swing.JButton();
        buscarNombreBg = new javax.swing.JPanel();
        textfieldNombre = new javax.swing.JTextField();
        sendBuscarNombre = new javax.swing.JButton();
        indicacionLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        buscarIDBg.setBackground(new java.awt.Color(255, 255, 255));

        indicacionLabel2.setForeground(new java.awt.Color(0, 0, 0));
        indicacionLabel2.setText("Ingrese el id del alumno");

        sendBuscarId.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/resourceEnviar.png")));
        sendBuscarId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBuscarIdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buscarIDBgLayout = new javax.swing.GroupLayout(buscarIDBg);
        buscarIDBg.setLayout(buscarIDBgLayout);
        buscarIDBgLayout.setHorizontalGroup(
            buscarIDBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarIDBgLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(buscarIDBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indicacionLabel2)
                    .addGroup(buscarIDBgLayout.createSequentialGroup()
                        .addComponent(formattfieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        buscarIDBgLayout.setVerticalGroup(
            buscarIDBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarIDBgLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(indicacionLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarIDBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendBuscarId, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(formattfieldId))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar (ID)", buscarIDBg);

        buscarEdadBg.setBackground(new java.awt.Color(255, 255, 255));

        indicacionLabel3.setForeground(new java.awt.Color(0, 0, 0));
        indicacionLabel3.setText("Ingrese la edad del alumno");

        sendBuscarEdad.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/resourceEnviar.png")));
        sendBuscarEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBuscarEdadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buscarEdadBgLayout = new javax.swing.GroupLayout(buscarEdadBg);
        buscarEdadBg.setLayout(buscarEdadBgLayout);
        buscarEdadBgLayout.setHorizontalGroup(
            buscarEdadBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEdadBgLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(buscarEdadBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indicacionLabel3)
                    .addGroup(buscarEdadBgLayout.createSequentialGroup()
                        .addComponent(formattfieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendBuscarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        buscarEdadBgLayout.setVerticalGroup(
            buscarEdadBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEdadBgLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(indicacionLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarEdadBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formattfieldEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendBuscarEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar (EDAD)", buscarEdadBg);

        buscarNombreBg.setBackground(new java.awt.Color(255, 255, 255));
        buscarNombreBg.setPreferredSize(new java.awt.Dimension(600, 300));

        sendBuscarNombre.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/resourceEnviar.png")));
        sendBuscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBuscarNombreMouseClicked(evt);
            }
        });

        indicacionLabel1.setForeground(new java.awt.Color(0, 0, 0));
        indicacionLabel1.setText("Ingrese el nombre del alumno");

        javax.swing.GroupLayout buscarNombreBgLayout = new javax.swing.GroupLayout(buscarNombreBg);
        buscarNombreBg.setLayout(buscarNombreBgLayout);
        buscarNombreBgLayout.setHorizontalGroup(
            buscarNombreBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarNombreBgLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(buscarNombreBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indicacionLabel1)
                    .addGroup(buscarNombreBgLayout.createSequentialGroup()
                        .addComponent(textfieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        buscarNombreBgLayout.setVerticalGroup(
            buscarNombreBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarNombreBgLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(indicacionLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarNombreBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendBuscarNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar (NOMBRE)", buscarNombreBg);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método se llama al hacer click en el botón para buscar por ID.
     * Obtiene el ID ingresado, valida que sea un número y realiza la consulta.
     * 
     * @param evt Evento de mouse click
     */
    private void sendBuscarIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBuscarIdMouseClicked
         if (tablaAlumnos == null) return;
        String texto = formattfieldId.getText().trim();
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el id a buscar.");
            return;
        }
        try {
            int id = Integer.parseInt(texto);
            ResultSet rs = operacionesBD.buscarAlumnoPorId(tablaAlumnos, id);
            mostrarResultados(rs);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para el id.");
        }
    }//GEN-LAST:event_sendBuscarIdMouseClicked

    /**
     * Este método se llama al hacer click en el botón para buscar por edad.
     * Obtiene la edad ingresada, valida que sea un número y realiza la consulta.
     * 
     * @param evt Evento de mouse click
     */
    private void sendBuscarEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBuscarEdadMouseClicked
        if (tablaAlumnos == null) return;
        String texto = formattfieldEdad.getText().trim();
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese la edad a buscar.");
            return;
        }
        try {
            int edad = Integer.parseInt(texto);
            ResultSet rs = operacionesBD.buscarAlumnoPorEdad(tablaAlumnos, edad);
            mostrarResultados(rs);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para la edad.");
        }
    }//GEN-LAST:event_sendBuscarEdadMouseClicked

    /**
     * Este método se llama al hacer click en el botón para buscar por nombre.
     * Obtiene el nombre ingresado y realiza la consulta.
     * 
     * @param evt Evento de mouse click
     */
    private void sendBuscarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBuscarNombreMouseClicked
        if (tablaAlumnos == null) return;
        String nombre = textfieldNombre.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el nombre a buscar.");
            return;
        }
        ResultSet rs = operacionesBD.buscarAlumnoPorNombre(tablaAlumnos, nombre);
        mostrarResultados(rs);
    }//GEN-LAST:event_sendBuscarNombreMouseClicked

    /**
     * Método ejecutar el cuadro de consultas jutno al lobby
     *
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new consultas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buscarEdadBg;
    private javax.swing.JPanel buscarIDBg;
    private javax.swing.JPanel buscarNombreBg;
    private javax.swing.JTextField formattfieldEdad;
    private javax.swing.JFormattedTextField formattfieldId;
    private javax.swing.JLabel indicacionLabel1;
    private javax.swing.JLabel indicacionLabel2;
    private javax.swing.JLabel indicacionLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton sendBuscarEdad;
    private javax.swing.JButton sendBuscarId;
    private javax.swing.JButton sendBuscarNombre;
    private javax.swing.JTextField textfieldNombre;
    // End of variables declaration//GEN-END:variables
}
