package BD_Alumnos.com.app.mvc.view;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import BD_Alumnos.com.app.mvc.view.lobby;
import java.net.URL;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author García Agustin Christian Santiago
 * @author Martínez Vera Josué Aldair
 * @author Mejía López Luis David
 * @author Solís Contreras Darian Giselle
 */
public class login extends javax.swing.JFrame {
    
    /** Controla la visibilidad de la contraseña */
    private boolean eyeNew = true;

    /**
     * Constructor de la clase login.
     * Inicializa los componentes gráficos de la interfaz y ajusta su posición.
     */
    public login() {
        initComponents(); // Método generado automáticamente por NetBeans
        this.setLocationRelativeTo(null); // Centra la ventana
        userfield.setMargin(new Insets(5, 10, 5, 5)); // Ajusta el margen del campo usuario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        iconPass = new javax.swing.JLabel();
        loginMessage = new javax.swing.JLabel();
        iconUser = new javax.swing.JLabel();
        eyeButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        userfield = new javax.swing.JTextField();
        passfield = new javax.swing.JPasswordField();
        seleccionBD = new javax.swing.JComboBox<>();
        iconPass1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanel.setBackground(new java.awt.Color(255, 255, 255));
        bgpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Bienvenido");
        bgpanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 80, 20));

        iconPass.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/resourceBD.png")));
        bgpanel.add(iconPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 30, 30));

        loginMessage.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        loginMessage.setForeground(new java.awt.Color(0, 0, 0));
        loginMessage.setText("LOGIN");
        bgpanel.add(loginMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 150, 70));

        iconUser.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/userIconPNG.png")));
        bgpanel.add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 239, 30, 40));

        eyeButton.setVisible(false);
        eyeButton.setBackground(null);
        eyeButton.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/resourceEyeO.png")));
        eyeButton.setBorderPainted(false);
        eyeButton.setContentAreaFilled(false);
        eyeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eyeButton.setFocusPainted(false);
        eyeButton.setFocusable(false);
        eyeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeButtonMouseClicked(evt);
            }
        });
        bgpanel.add(eyeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 30, 40));

        sendButton.setBackground(new Color(30,30,30));
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Enviar");
        sendButton.setBorder(null);
        sendButton.setBorderPainted(false);
        sendButton.setFocusPainted(false);
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        bgpanel.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 57, 30));

        userfield.setEditable(false);
        userfield.setBackground(new Color(30,30,30));
        userfield.setForeground(new java.awt.Color(102, 102, 102));
        userfield.setText("Usuario");
        userfield.setToolTipText("");
        userfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        userfield.setCaretColor(new java.awt.Color(30, 30, 30));
        userfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userfieldMouseClicked(evt);
            }
        });
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });
        bgpanel.add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 290, 40));

        passfield.setEditable(false);
        passfield.setBackground(new Color(30,30,30));
        passfield.setForeground(new java.awt.Color(102, 102, 102));
        passfield.setText("Contraseña");
        passfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        passfield.setCaretColor(new java.awt.Color(255, 255, 255));
        passfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passfieldMouseClicked(evt);
            }
        });
        bgpanel.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 290, 40));
        passfield.setEchoChar((char) 0);

        seleccionBD.setBackground(new java.awt.Color(56, 56, 56));
        seleccionBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "anahuac", "iuv_universidad", "universidad_veracruzana", "tecnologico_xalapa", "normal_veracruzana", "universidad_xalapa", "universidad_euro" }));
        bgpanel.add(seleccionBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 290, 30));

        iconPass1.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/passIconPNG.png")));
        bgpanel.add(iconPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 300, 30, 36));

        getContentPane().add(bgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que se dispara al hacer clic en el campo de usuario.
     * Permite editar el campo y limpia el placeholder si está presente.
     * 
     * @param evt Evento del mouse
     */
    private void userfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userfieldMouseClicked
        userfield.setEditable(true);
        if (userfield.getText().equals("Usuario")){
            userfield.setText("");
            userfield.setForeground(new Color(195,195,195));
            userfield.setCaretColor(Color.white);
        }
    }//GEN-LAST:event_userfieldMouseClicked

    /**
     * Evento que se dispara al hacer clic en el campo de contraseña.
     * Permite editar el campo y limpia el placeholder si está presente.
     * 
     * @param evt Evento del mouse
     */
    private void passfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passfieldMouseClicked
        passfield.setEditable(true);
        eyeButton.setVisible(true);
        if (String.valueOf(passfield.getPassword()).equals("Contraseña")){
            passfield.setText("");
            passfield.setEchoChar('*');
            passfield.setForeground(new Color(195,195,195));
            passfield.setCaretColor(Color.white);
        }
    }//GEN-LAST:event_passfieldMouseClicked

    /**
     * Evento de acción del campo usuario (actualmente no implementado).
     * 
     * @param evt Evento de acción
     */
    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    /**
     * Evento que se dispara al hacer clic en el botón "Enviar".
     * Verifica los campos, establece conexión a la base de datos
     * y redirige al lobby si la autenticación es exitosa.
     * 
     * @param evt Evento del mouse
     */
    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        passfield.setEchoChar('*');
        String usuario = userfield.getText().trim();
        String contrasena = new String(passfield.getPassword()).trim();
        String nombreBD = seleccionBD.getSelectedItem().toString();

        // Elimina el placeholder antes de validar
        if (usuario.equals("Usuario")) usuario = "";
        if (contrasena.equals("Contraseña")) contrasena = "";

        // Validación de campos vacíos
        if (usuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
            return;
        }

        // Establece conexión con la base de datos
        Connection conn = BD_Alumnos.com.app.mvc.controller.ConexionBD.getConexion(usuario, contrasena, nombreBD);

        if (conn != null) {
            // Guarda los datos de sesión para uso posterior
            BD_Alumnos.com.app.mvc.controller.Sesion.iniciarSesion(usuario, contrasena, nombreBD);

            JOptionPane.showMessageDialog(this, "¡Conexión exitosa a la base de datos '" + nombreBD + "'!");

            // Ir al lobby
            lobby goLobby = new lobby();
            goLobby.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al conectar. Verifique usuario, contraseña o nombre de la base de datos.");
        }
    }//GEN-LAST:event_sendButtonMouseClicked

    /**
     * Evento que se dispara al hacer clic en el botón del "ojo".
     * Alterna la visibilidad del texto en el campo de contraseña.
     * 
     * @param evt Evento del mouse
     */
    private void eyeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeButtonMouseClicked
         if (eyeNew) {
                eyeButton.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/resourceEyeC.png")));
                passfield.setEchoChar((char)0);
        } else {
                eyeButton.setIcon(new ImageIcon(getClass().getResource("/BD_Alumnos/com/app/mvc/images/resourceEyeO.png")));
                passfield.setEchoChar('*');
        }
        eyeNew = !eyeNew; // Alternar estado                
    }//GEN-LAST:event_eyeButtonMouseClicked

    /**
     * Evento de acción del botón enviar (no implementado).
     * 
     * @param evt Evento de acción
     */
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * Método principal. Inicia la interfaz de login.
     * 
     * @param args Argumentos desde línea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgpanel;
    private javax.swing.JButton eyeButton;
    private javax.swing.JLabel iconPass;
    private javax.swing.JLabel iconPass1;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel loginMessage;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JComboBox<String> seleccionBD;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField userfield;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
